image: node:18

pipelines:
  default:
    - parallel:
        - step:
            name: Install Dependencies
            caches:
              - node
            script:
              - npm install
        - step:
            name: Build Project in Library Mode
            script:
              - npm run build:lib
        - step:
            name: Deploy to Development
            deployment: staging
            script:
              - echo "Deploying project..."
              - scp -r dist/ root@137.184.226.115:/home/revad/ricochet-chat-bot-front
              
definitions:
  caches:
    node: node_modules
